#菜单相关
menu:
  main: |
    💠 每日打卡 :: Daily Attendance
    - 打卡 » 快速打卡（智能判断打卡）
    - /da ka » 快速打卡（同上）
    - /da wake » 早起打卡
    - /da nap » 午睡打卡
    - /da sleep » 晚安打卡
    - /da run » 运动打卡
    - /da use » 使用道具
    - /da exch » 兑换凭证
    - /da info » 查询信息
    - /da rank » 排行榜
    - /da about » 关于本应用
    - /da set » 个人设定
  put: "- /da put » 群聊设定"



doNotHaveTasks: "💠 当前没有需要打卡的任务。"


about: |
  💠 每日打卡 | 关于本应用
  - 开发者：@Rominwolf
  - 开源页：https://github.com/Rominwolf/daily-attendance-mirai
  - 特别鸣谢所有曾经帮助过设计、制作并完善本应用的所有用户！


# 用户信息相关
info:
  menu: |
    💠 每日打卡 | {name}的信息
    1. 查询资源信息
    2. 查询打卡信息
    __________
    ❕ 发送「/da info <序号>」来查询目标信息，如“/da info 1”将查询{name}的资源信息。
  tipAt: 在消息最后艾特其他用户可查询目标用户的信息。
  resource: |
    💠 每日打卡 | {name}的资源信息
    🎫 凭证：{score} 张
    💼 道具：
    - 夜光蜡烛：{candle} 支
    - 筹码摇杆：{rocker} 个
    - 翻倍骰子：{dice} 个
    - 无字白纸：{paper} 张
    - 好运风铃：{lucky} 个
  attendance: |
    💠 每日打卡 | {name}的打卡信息
    🌅 早起打卡（{wake_remind}提醒）//
    - 最后打卡于 {wake_short}
    - 累计打卡 {wake_total} 次；本月打卡 {wake_total_month} 天；本月连续打卡 {wake_total_continuous} 天
    💤 午睡打卡（{nap_remind}提醒）//
    - 最后打卡于 {nap_short}
    - 累计打卡 {nap_total} 次；本月打卡 {nap_total_month} 天；本月连续打卡 {nap_total_continuous} 天
    🌃 晚安打卡（{sleep_remind}提醒）//
    - 最后打卡于 {sleep_short}
    - 累计打卡 {sleep_total} 次；本月打卡 {sleep_total_month} 天；本月连续打卡 {sleep_total_continuous} 天
    🏃‍ 运动打卡（{run_check}检测） //
    - 最后打卡于 {run_short}
    - 累计打卡 {run_total} 次；本月打卡 {run_total_month} 天；本月连续打卡 {run_total_continuous} 天
    - 历史最多活跃 {run_step_max} 步；上次活跃 {run_step_last} 步




# 使用道具相关
use:
  #    筹码摇杆🕹：使用后并连续打卡一周，你投入的 50 张凭证就能赢回双倍。
  #    无字白纸📃：下次参与打卡后会在该奖池中扔下这张纸，在开奖时拿到纸张的用户只会获得 1 张凭证。
  #    好运风铃🎐：自使用日起至本月底参与打卡将更容易获得更好的奖励。
  menu: |
    💠 每日打卡 | 支持的道具：
    1. 夜光蜡烛🕯：点燃蜡烛后即使参与了晚安打卡，发言也不会被记作打卡失败。
    2. 翻倍骰子🎲：掷骰子后，你下次参与任意打卡所获得的奖励将随机翻 1 ~ 3 倍。
    __________
    ❕ 发送「/da use <序号>」来使用指定道具，如“/da use 1”将使用一支夜光蜡烛。
  notExist: "❌ 目标序号的道具不存在或暂不允许使用。"
  candle:
    success: "🕯 已成功使用一支夜光蜡烛，从现在开始到明早晚安打卡结束你的发言将不会被记录。"
    notEnough: "❌ 啊哦…你目前没有足够的夜光蜡烛用以使用。"
    alreadyUsed: "✅ 今夜你已经使用了一支夜光蜡烛，请尽情发言吧！"
  dice:
    success: "🎲 已成功使用一枚翻倍骰子，下次参与任意打卡所获得的奖励将随机翻 1 ~ 3 倍。"
    notEnough: "❌ 啊哦…你目前没有足够的翻倍骰子用以使用。"
    alreadyUsed: "✅ 你已经使用了一枚翻倍骰子，下次打卡获得的奖励有可能翻倍哦！"



# 提醒打卡相关
remind:
  # 私聊提醒打卡支持变量：
  # {nick} -> 目标用户的昵称
  # {total} -> 目标用户的指定打卡类型的累计打卡次数
  # {cont} -> 目标用户的指定打卡类型的连续打卡次数
  # {botName} -> 机器人的名字
  private:
    list:
      - "Howdy！我是你的私人提醒小助手 —— {botName}！\n
        一条友好的提醒：现在你可以参与“{type}”了，发送「{cmd}」命令来打卡吧！"
      - "你好，{nick}！别忘记现在可以参与{type}，发送「{cmd}」命令即可打卡。"
      - "(｡･∀･)ﾉﾞ嗨！这里是{botName}！一起来参与{type}吧！\n
        发送「{cmd}」命令即可一键加入！"
      - "{nick}，赞哦！今天也继续保持{type}吧！\n
        发送「{cmd}」命令即可一键加入！"
      - "🔥 {nick}！你真的势不可挡！\n
        为了让这股{type}之火继续熊熊燃烧，现在就发送「{cmd}」命令加入打卡吧！"
      - "一起来参与{type}，让雪球开心起来！\n
        发送「{cmd}」命令即可一键加入！"
      - "哦吼！{type}时间到！现在就发送「{cmd}」命令加入打卡吧！"
      - "{nick}！现在就来完成一个{type}，保持{cont}天连签战绩！\n
        现在就发送「{cmd}」命令加入打卡！"
      - "嗨，你已经保持了{cont}天连签！现在发送「{cmd}」命令加入打卡，让连签战绩不清空！"
      - "是我，{botName}。今天{type}不？反正发送「{cmd}」命令就能加入打卡。\n
         我是懒得管你……喂！不许给我家长打小报告！！"
      - "是我，{botName}。{cont} 天连续{type}，也凑活吧。\n
         发送「{cmd}」命令加入打卡，打不打随你。\n
         提醒你打卡只是我家长给我的任务，本小姐可没兴趣！"
      - "哇！你势不可挡！来创造{type} {cont} 天连续打卡的神话！\n
         发送「{cmd}」命令加入打卡！"
      - "今天不打卡，就真的跟连续{type}无缘了！不能再等了，快来{type}呀！\n
         因为我真的不忍心看你后悔的样子~~发送「{cmd}」命令加入打卡~"
      - "诶嘿，{botName}来啦！\n
         我是你的每日{type}提醒小助手，用一句话（指「{cmd}」命令）的时间，换来打卡成功！"
      - "你好！我是{botName}！
         想不想来一起参与{type}？发送「{cmd}」命令加入打卡。"
      - "打卡之神是怎么练成的？每天打次卡，持之以恒不放弃 —— 就是这样！\n
         发送「{cmd}」命令加入打卡。"
      - "🥰💕👋 哈喽哈喽！！我是{botName}～\n
         哎哟！这可不得了！一想到你马上就要参与{type}我就好激动！我们马上开始打卡好不好！？\n
         发送「{cmd}」命令加入打卡！"
      - "是我，{botName}。{type}了没？哼。我就知道！趁我现在还没有降低对你的评价，立刻进行打卡！\n
         发送「{cmd}」命令加入打卡。"
      - "是我，{botName}。我是来提醒你现在可以{type}打卡了。\n
         打不打卡你随便，我没兴趣盯着你！\n
         发送「{cmd}」命令加入打卡。"
      - "🥰💕👋 嗨~~我是{botName}！为了你，小美叫我去战场我也不去了！知道你对我有多重要了吗？\n
         嗯，一想到你马上就要参与{type}了我就好开心！一起加油吧！\n
         发送「{cmd}」命令加入打卡。"
      - "到时间啦，可以参加今天的{type}了哦！\n
         什么。你不想打卡吗。\n
         没关系的，我不会伤心的，你不打卡也可以的，我绝对不会伤心的。\n
         你真的不想打卡吗？（三步并做两步走到马路上，一辆大货车飞驰而来）\n
         发送「{cmd}」命令加入打卡。"
      - "什…你说你不想打卡……？\n
         唉，终究还是错付了，我鼓足勇气，好不容易做了决定，迈出这一步，向你发了这条消息……\n
         现在已经没有回头路了，我只好再迈一步了。\n
         发送「{cmd}」命令加入打卡。"
  group:
    list:
      - "大家好！我是本群的提醒打卡小助手 —— {botName}！\n
        我是来提醒各位现在可以进行“{type}”了，发送「{cmd}」命令来参与打卡吧！"
      - "(｡･∀･)ﾉﾞ嗨！这里是{botName}！一起来参与{type}吧！\n
        发送「{cmd}」命令即可一键加入！"
      - "🔥 让我康康是谁燃起来了——原来是大家！\n
        各位真的势不可挡！\n
        为了让这股{type}之火继续熊熊燃烧，现在就发送「{cmd}」命令加入打卡吧！！"
      - "哦吼！{type}时间到！现在就发送「{cmd}」命令加入打卡吧！"
      - "一起来参与{type}，让雪球开心起来！\n
        发送「{cmd}」命令即可一键加入！"
      - "是我，{botName}。今天{type}不？反正发送「{cmd}」命令就能加入打卡。\n
         我是懒得管你们……喂！不许给我家长打小报告！！"
      - "是我，{botName}。连续{type}这么多天？也凑活吧。\n
         发送「{cmd}」命令加入打卡，打不打随你。\n
         提醒大家打卡只是我家长给我的任务，本小姐可没兴趣！"
      - "哇！大家真的势不可挡！来创造{type}新的神话！\n
         发送「{cmd}」命令加入打卡！"
      - "今天不打卡，{type}的连续打卡就无缘了！不能再等了，快来{type}呀！\n
         因为我真的不忍心看大家后悔的样子~~发送「{cmd}」命令加入打卡~"
      - "诶嘿，{botName}来啦！\n
         我是各位的每日{type}提醒小助手，用一句话（指「{cmd}」命令）的时间，换来打卡成功！"
      - "你好！我是{botName}！
         想不想来一起参与{type}？发送「{cmd}」命令加入打卡。"
      - "打卡之神是怎么练成的？每天打次卡，持之以恒不放弃 —— 就是这样！\n
         发送「{cmd}」命令加入打卡。"
      - "🥰💕👋 哈喽哈喽！！我是{botName}～\n
         哎哟！这可不得了！一想到大家马上就要参与{type}我就好激动！我们马上开始打卡好不好！？\n
         发送「{cmd}」命令加入打卡！"
      - "是我，{botName}。{type}了没？哼。我就知道！趁我现在还没有降低对各位的评价，立刻进行打卡！\n
         发送「{cmd}」命令加入打卡。"
      - "是我，{botName}。我是来提醒大家现在可以{type}打卡了。\n
         打不打卡都随便，我没兴趣盯着看！\n
         发送「{cmd}」命令加入打卡。"
      - "🥰💕👋 嗨~~我是{botName}！为了大家，小美叫我去战场我也不去了！知道各位对我有多重要了吗？\n
         嗯，一想到大家马上就要参与{type}了我就好开心！一起加油吧！\n
         发送「{cmd}」命令加入打卡。"
      - "到时间啦，可以参加今天的{type}了哦大家！\n
         什么。各位不想打卡吗。\n
         没关系的，我不会伤心的，你不打卡也可以的，我绝对不会伤心的。\n
         各位真的不想打卡吗？（三步并做两步走到马路上，一辆大货车飞驰而来）\n
         发送「{cmd}」命令加入打卡。"
      - "什…你们说不想打卡……？\n
         唉，终究还是错付了，我鼓足勇气，好不容易做了决定，迈出这一步，向这个群发了这条消息……\n
         现在已经没有回头路了，我只好再迈一步了。\n
         发送「{cmd}」命令加入打卡。"



# 凭证 -> 第三方货币相关
exchange:
  menu: |
    💠 每日打卡 | 凭证兑换成{name}
    - /da exch <数量>：将凭证以 {rate} 的比率兑换成{name}。
    __________
    ❕ 如“/da exch 10”将兑换 10 张凭证到 {money} {unit}{name}。
  tooLarge: "💠 你至少需要 {score} 张凭证才能兑换成 {money} {unit}{name}。"
  tooSmall: "💠 请兑换至少 1 张凭证。"
  success: "💠 已成功将 {score} 张凭证兑换成 {money} {unit}{name}。"
  failed: "💠 暂时无法进行兑换，请稍后再试。"



# 用户设定相关
set:
  menu: |
    💠 每日打卡 | 个人打卡设定：
    - /da set remind <打卡> <状态>
    说明：开启或关闭指定打卡是否接收“打卡提醒”的消息
    - /da set run <状态>
    说明：开启或关闭运动打卡的自动步数检测
    __________
    <打卡>：必填，欲更新的打卡类型，允许：wake（早起打卡）、nap（午睡打卡）、sleep（晚安打卡）
    <状态>：必填，欲更新的数据元素，允许：on（开启）、off（关闭）
  successRemindOn: |
    💠 每日打卡 | 个人打卡设定：
    ✅ 已成功开启{type}的每日提醒，现在我会在每天的打卡时间段内以私聊的形式发给你打卡提醒。
  successRemindOff: |
    💠 每日打卡 | 个人打卡设定：
    ✅ 已关闭{type}的每日提醒。今后改变心意了你可以随时开启。
  successRunCheckOn: |
    💠 每日打卡 | 个人打卡设定：
    ✅ 已开启运动打卡的自动步数检测，我会在每晚 11 点自动检测你当日是否完成了要求步数。
  successRunCheckOff: |
    💠 每日打卡 | 个人打卡设定：
    ✅ 已关闭运动打卡的自动步数检测。今后改变心意了你可以随时开启。
  failUnknownType: |
    💠 每日打卡 | 个人打卡设定：
    ❌ 未知的打卡类型，请发送「/da set」命令查询目前支持的所有打卡类型。
  failUnknownStatus: |
    💠 每日打卡 | 个人打卡设定：
    ❌ 未知的状态，请使用全小写的半角英文字母，如“on”或“off”。



# 群设定相关
put:
  menu: |
    💠 每日打卡 | 群聊打卡设定：
    - 早起打卡提醒：{wake_remind}
    - 午睡打卡提醒：{nap_remind}
    - 晚安打卡提醒：{sleep_remind}
    __________
    - /da put remind <打卡> <状态>
    说明：开启或关闭指定打卡是否接收“打卡提醒”的消息
    <打卡>：必填，欲更新的打卡类型，允许：wake（早起打卡）、nap（午睡打卡）、sleep（晚安打卡）
    <状态>：必填，欲更新的数据元素，允许：on（开启）、off（关闭）
  successRemindOn: |
    💠 每日打卡 | 群聊打卡设定：
    ✅ 已成功开启{type}的每日提醒，现在我会在每天的打卡时间段内发送一条打卡提醒到本群。
  successRemindOff: |
    💠 每日打卡 | 群聊打卡设定：
    ✅ 已关闭{type}的每日提醒。但你可以使用「/da set」命令开启私聊提醒功能。
  failUnknownType: |
    💠 每日打卡 | 群聊打卡设定：
    ❌ 未知的打卡类型，请发送「/da put」命令查询目前支持的所有打卡类型。
  failUnknownStatus: |
    💠 每日打卡 | 群聊打卡设定：
    ❌ 未知的状态，请使用全小写的半角英文字母，如“on”或“off”。
  failPermission: |
    💠 每日打卡 | 群聊打卡设定：
    ❌ 你的权限不足，无法更新本群的设定。权限要求为本群的管理员或群主。
  failGroupOnly: |
    💠 每日打卡 | 群聊打卡设定：
    ❌ 该命令仅限群聊使用。



# 早起打卡相关
wake:
  name: "早起打卡"
  youAlreadyJoined: "你今天已经参与早起打卡了，但你还可以参与今天的午睡打卡！"
  tooEarly: "打卡时间未到，早起打卡时间为：每日 {start}:00 - {end}:00。"
  tooLate: "打卡时间已过，早起打卡时间为：每日 {start}:00 - {end}:00。"
  joined: |
    ✅ 今日早起打卡成功！
    {lucky}！早起打卡奖池 +{score} 凭证，目前奖池共有 {pool} 张凭证。
    开奖时间为今日 {end}:00，届时将以私聊的形式发送结果，请注意查收。
  pool: |
    🎫 今日早起打卡奖池已开奖！
    你获得了 {score} 张凭证，今日奖池内共 {pool} 张凭证。



# 午睡打卡相关
nap:
  name: "午睡打卡"
  youAlreadyJoined: "你今天已经参与午睡打卡了，但你还可以参与今天的晚安打卡！"
  tooEarly: "打卡时间未到，午睡打卡时间为：每日 {start}:00 - {end}:00。"
  tooLate: "打卡时间已过，午睡打卡时间为：每日 {start}:00 - {end}:00。"
  success: |
    ✅ 今日午睡打卡成功！
    {lucky}！本次打卡你获得了 {amount} {unit}{resource}，你有 {prob}% 的几率获得该物品。



# 晚安打卡相关
sleep:
  name: "晚安打卡"
  youAlreadyJoined: "你今天已经参与晚安打卡了，但你还可以参与明天的早起打卡！"
  tooEarly: "打卡时间未到，晚安打卡时间为：每日 {start}:00 - {end}:00。"
  tooLate: "打卡时间已过，晚安打卡时间为：每日 {start}:00 - {end}:00。"
  joined: |
    ✅ 今日晚安打卡成功，现在开始请不要再发言。
    {lucky}！晚安打卡奖池 +{score} 凭证，目前奖池共有 {pool} 张凭证。
    开奖时间为明日 06:00，届时将以私聊的形式发送结果，请注意查收。
  pool: |
    🎫 昨日晚安打卡奖池已开奖！
    你获得了 {score} 张凭证，昨夜奖池内共 {pool} 张凭证。
  talkingWarn: |
    ❗ 请注意，你已参与了今日的晚安打卡，请不要{active}，再活跃 {times} 次将打卡失败。
    🕯 夜光蜡烛可让你今夜自由活跃，发送「/da use 1」命令来使用本道具。
  failed: "❌ 因为你今夜活跃次数超过 3 次，晚安打卡已失败。明天再来打卡吧！"



# 运动打卡相关
run:
  name: "运动打卡"
  intro: |
    💠 每日打卡 | 运动打卡介绍
    - 说明：每天 23:50 自动检测步数，当日步数达到 5,000 步即打卡成功。
    - 奖励：每达成 5,000 步则 +1 张凭证，至多可获得 4 张凭证。
    - 加入：成为我的好友并开启你的QQ运动的“加入运动排行”功能会自动加入（访问 https://u3u.app/8xee 查看步骤）
  success: |
    ✅ 今日运动打卡成功！
    你今天跑了 {step} 步！{new_top}
    本次打卡获得了 {score} 张凭证。
  newTop: "创新高！"


# 连续打卡相关
continuous:
  result: |
    ✅ 你已保持本月连续{type} {day} 天，获得奖励：{name} * {amount}。


# 排行榜相关
rank:
  menu: |
    💠 每日打卡 | 获取指定排行榜：
    {list}__________
    发送「/da rank <序号>」来查看指定排行，如“/da rank 1”将查看用户所持凭证的排名列表。
  menuMap:
    1: 用户所持凭证排名
    11: 累计参与早起打卡排名
    12: 累计参与午睡打卡排名
    13: 累计参与晚安打卡排名
    14: 累计参与运动打卡排名
    21: 运动打卡历史步数排名
    22: 运动打卡上次步数排名
  result: |
    💠 每日打卡 | {name}
    {list}
  list: "{index}. {you}{crown}{name}（{amount}{unit}）\n" # 1. 姓名（24支）



# 控制台相关
terminal:
  desc: |
    /da <user/group> <id> <类型> <数据>    # 每日打卡 控制台命令集
  success: |
    已成功将地址 {id} 的路径 {path} 的值更改为 {new_value}，原数据为 {old_value}。



# 获得的凭证数量，以阶层增加
lucky:
  - "史诗"
  - "手气不错"
  - "传奇"
  - "金色传说"



# 系统内置相关
system:
  you: "你"
  thisGroup: "本群"
  thisGuy: "那个人"
  unknown: "未知"

  emoji:
    handsUp: "✋"
    crown: "👑"

  turnOn: "开启"
  turnOff: "关闭"

  got: "已获得"
  notGet: "未拥有"

  ago:
    year: "年前"
    day: "天前"
    hour: "小时前"
    minute: "分钟前"
    second: "秒前"
    moment: "刚刚"

  # 活跃类型
  active:
    talk: "发送消息"
    nudge: "戳一戳"
    recall: "撤回消息"

  # 资源名组
  resource:
    exchange: "雪花" #第三方货币名称
    score: "凭证"
    candle: "夜光蜡烛"
    rocker: "筹码摇杆"
    dice: "翻倍骰子"
    paper: "无字白纸"
    lucky: "好运风铃"

  # 量词组：代表的是目标资源的量词单位（如：X 张 凭证）
  unit:
    exchange: "片" #第三方货币单位
    times: "次"
    score: "张"
    candle: "支"
    rocker: "个"
    dice: "枚"
    paper: "张"
    lucky: "个"
    step: "步"
