# 早起打卡相关
wake:
  start: 6 #打卡开启时间 (X:00:00)
  end: 9 #打卡关闭时间 (Y:00:00)
  settle: 9 #打卡结算时间 (Z:00:00)
  continuous: #连续打卡的奖励列表
    week: #每连续打卡7天
      id: "dice" #奖励ID
      amount: 1 #奖励个数
    month: #连续打卡1月
      id: "lucky"
      amount: 1

# 午睡打卡相关
nap:
  start: 12
  end: 15
  settle: 15
  awards: # 午睡打卡可获得的奖励列表
    # 一个奖励，键名格式为“start-end”，其中start为起始值（包括），end为结束值（不包括），范围限制在0-100；
    # 当键名为“default“则表示为默认奖励（即找不到目标结果时获得的奖励，仅限1条）
    "default":
      id: "score" # 资源ID
      amount: 1 # 获取的数量
      rarity: 0 # 稀有度（越大表示越难以获得，从0开始）
    "0-42":
      id: "score"
      amount: 1
      rarity: 0
    "42-90":
      id: "score"
      amount: 2
      rarity: 1
    "90-98":
      id: "score"
      amount: 3
      rarity: 2
    "98-100":
      id: "candle"
      amount: 1
      rarity: 3

# 晚安打卡相关
sleep:
  start: 21
  end: 24
  settle: 6
  continuous: #连续打卡的奖励列表
    week: #每连续打卡7天
      id: "paper" #奖励ID
      amount: 1 #奖励个数
    month: #连续打卡1月
      id: "dice"
      amount: 1


# 运动打卡相关
run:
  status: true #运动打卡是否开启
  check: 23 #每日检测步数的时间（小时）
  continuous: #连续打卡的奖励列表
    week: #每连续打卡7天
      id: "rocker" #奖励ID
      amount: 1 #奖励个数
    month: #连续打卡1月
      id: "dice"
      amount: 1

# 凭证兑换相关（注意修改语言包内 system.resource/unit 的数据）
exchange:
  # 第三方应用的命令行
  # 允许变量：{targetId} -> 欲兑换的QQ号；{amount} -> 本次兑换的数量（向下取整）
  command: "sb user {targetId} favor +{amount}"
  rate: "1:1" #凭证与第三方货币的兑换比例